language: node_js
node_js:
  - node
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.13.0
  - export PATH=$HOME/.yarn/bin:$PATH
  - docker-compose up -d
  - yarn global add codecov
before_script:
  - yarn prisma deploy
  - yarn codegen
after_success:
  - codecov
cache:
  yarn: true
env:
  APP_SECRET=app-secret-for-testing
  DB_USER=prisma
  DB_PASSWORD=prisma
  NODE_ENV=test
  PRISMA_ENDPOINT=http://localhost:4466/wobbly
  PRISMA_MANAGEMENT_API_SECRET=prisma-management-secret-for-testing
  PRISMA_SECRET=prisma-secret-for-testing
  REDIS_URL=redis://localhost:6379
